# -*- coding: utf-8 -*-
"""modis_7days.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kGYrcdb-4UsQ-AtmNyYponlGOvKZmzBC
"""

import plotly.graph_objects as go

import pandas as pd

df = pd.read_csv('./MODIS_C6_Global_7d.csv')

"""Author @ Amartya | Nasa International Space App Challenge 2020"""

df

df['text'] = 'Date and Time:' + df['acq_date'].astype(str) + ':' + df['acq_time'].astype(str) + ', ' + df['satellite'].astype(str) + ', ' + df['daynight'].astype(str)

df['text']

fig = go.Figure(data=go.Scattergeo(
        lon = df['longitude'],
        lat = df['latitude'],
        text = df['text'],
        mode = 'markers',
        marker_color = df['brightness'],
        ))

fig.update_layout(
        title = 'NASA Fire Information for Resource Management System (FIRMS)<br>(MODIS 1km 7 Day Data)',
        geo_scope='world',
    )
fig.show()

fig.update_layout(
        title = 'NASA Fire Information for Resource Management System (FIRMS)<br>(MODIS 1km 7 Day Data)',
        geo_scope='usa',
    )
fig.show()