# -*- coding: utf-8 -*-
"""mopitt_data_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bb_9kuO0Suo5761xgJioS84TrEdR5ojj
"""

import pandas as pd
df = pd.read_csv('MOP02J-20200101-L2V18.0.3.csv')
df.head()

df

tx = df[0:5000]

tx

import plotly.express as px

fig4 = px.density_mapbox(tx, lat='# Latitude', lon=' Longitude', z=' COTotalColumn', radius=10,
                        center=dict(lat=0, lon=180), zoom=0,
                        mapbox_style="stamen-terrain")
fig4.show()

import chart_studio

import chart_studio.plotly as py
import chart_studio.tools as tls

pip install chart_studio

username = 'saikia'
api_key = 'oIIOTBZOlv8hbx8XorKH'

chart_studio.tools.set_credentials_file(username=username, api_key=api_key)

py.plot(fig4, filename = 'csa-mopitt', auto_open=True)

