# -*- coding: utf-8 -*-
"""SUOMI_VIIRS_C2_Global_24h.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqyiyklyiMLmPl_IJBsryJdYPtWhbQo8

Author @ Amartya | Nasa International Space App Challenge 2020
"""

import plotly.graph_objects as go

import pandas as pd

df = pd.read_csv('./SUOMI_VIIRS_C2_Global_24h.csv')

df

df['text'] = 'Date and Time:' + df['acq_date'].astype(str) + ':' + df['acq_time'].astype(str) + ', ' + df['satellite'].astype(str) + ', ' + df['daynight'].astype(str)

df['text']

fig = go.Figure(data=go.Scattergeo(
        locationmode = 'USA-states',
        lon = df['longitude'],
        lat = df['latitude'],
        text = df['text'],
        mode = 'markers',
        marker = dict(
            size = 8,
            opacity = 0.8,
            reversescale = True,
            autocolorscale = False,
            symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            ),
            colorscale = 'Reds',
            cmin = 0,
            color = df['bright_ti4'],
            cmax = df['bright_ti4'].max(),
            colorbar_title="Brightness Level<br>24h data"
        )))

fig.update_layout(
        title = 'NASA FIRMS - VIIRS 375m / S-NPP & / NOAA-20',
        geo = dict(
            scope='usa',
            projection_type='albers usa',
            showland = True,
            landcolor = "rgb(250, 250, 250)",
            subunitcolor = "rgb(217, 217, 217)",
            countrycolor = "rgb(217, 217, 217)",
            countrywidth = 0.5,
            subunitwidth = 0.5
        ),
    )
fig.show()

fig = go.Figure(data=go.Scattergeo(
        locationmode = 'ISO-3',
        lon = df['longitude'],
        lat = df['latitude'],
        text = df['text'],
        mode = 'markers',
        marker = dict(
            size = 8,
            opacity = 0.8,
            reversescale = True,
            autocolorscale = False,
            symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            ),
            colorscale = 'Reds',
            cmin = 0,
            color = df['bright_ti4'],
            cmax = df['bright_ti4'].max(),
            colorbar_title="Brightness Level<br>24h data"
        )))

fig.update_layout(
        title = 'NASA FIRMS - VIIRS 375m / S-NPP & / NOAA-20',
        geo = dict(
            scope='world',
            projection_type='azimuthal equal area',
            showland = True,
            landcolor = "rgb(250, 250, 250)",
            subunitcolor = "rgb(217, 217, 217)",
            countrycolor = "rgb(217, 217, 217)",
            countrywidth = 0.5,
            subunitwidth = 0.5
        ),
    )
fig.show()

xtt = df[0:5000]

xtt['text'] = 'Date and Time:' + xtt['acq_date'].astype(str) + ':' + xtt['acq_time'].astype(str) + ', ' + xtt['satellite'].astype(str) + ', ' + xtt['daynight'].astype(str)

figu = go.Figure(data=go.Scattergeo(
        locationmode = 'USA-states',
        lon = xtt['longitude'],
        lat = xtt['latitude'],
        text = xtt['text'],
        mode = 'markers',
        marker = dict(
            size = 8,
            opacity = 0.8,
            reversescale = True,
            autocolorscale = False,
            symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            ),
            colorscale = 'Reds',
            cmin = 0,
            color = xtt['bright_ti4'],
            cmax = xtt['bright_ti4'].max(),
            colorbar_title="Brightness Level<br>24h data"
        )))

figu.update_layout(
        title = 'NASA FIRMS - VIIRS 375m / S-NPP & / NOAA-20',
        geo = dict(
            scope='usa',
            projection_type='albers usa',
            showland = True,
            landcolor = "rgb(250, 250, 250)",
            subunitcolor = "rgb(217, 217, 217)",
            countrycolor = "rgb(217, 217, 217)",
            countrywidth = 0.5,
            subunitwidth = 0.5
        ),
    )
fig.show()

figu.update_layout(
        title = 'NASA FIRMS - VIIRS 375m / S-NPP & / NOAA-20',
        geo = dict(
            scope='world',
            projection_type='azimuthal equal area',
            showland = True,
            landcolor = "rgb(250, 250, 250)",
            subunitcolor = "rgb(217, 217, 217)",
            countrycolor = "rgb(217, 217, 217)",
            countrywidth = 0.5,
            subunitwidth = 0.5
        ),
    )
fig.show()

import chart_studio
import chart_studio.plotly as py
import chart_studio.tools as tls

pip install chart_studio

username = 'saikia'
api_key = 'oIIOTBZOlv8hbx8XorKH'

chart_studio.tools.set_credentials_file(username=username, api_key=api_key)

py.plot(figu, filename = 'viirs', auto_open=True)

